# Alpine Linux with OpenJDK JRE
FROM openjdk:8-jre-alpine
ENV SERVICE_MODULE tct-service
# Define environment variable
#ENV NAME World
ENV TZ 'Asia/Ho_Chi_Minh'
ENV KEY_OPTS '-Djavax.net.ssl.trustStore=tct-cert/live-TCTThue/esb-gdt-gov.jks -Djavax.net.ssl.trustStorePassword=123456'

# Install any needed packages
RUN apk add --no-cache bash
RUN apk add --no-cache tzdata
RUN apk add vim
RUN apk add --update htop

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN echo "alias tailf='tail -f -n'" >> ~/.bashrc
RUN echo "alias ll='ls -alF'" >> ~/.bashrc
RUN ["/bin/bash", "-c", "source ~/.bashrc"]

RUN mkdir -p /app/conf

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY ./script/entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh
COPY ./target/${SERVICE_MODULE} /app/jars
COPY ./${SERVICE_MODULE}/data-xml-base /app/data-xml-base
COPY ./${SERVICE_MODULE}/tct-cert /app/tct-cert

# Make port  available to the world outside this container
EXPOSE 19401

# Run service when the container launches
CMD ["./entrypoint.sh"]
