server:
    #    address: 0.0.0.0
    port: 18301
spring:
    application:
        name: '@project.artifactId@'
    datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        hikari:
            connection-timeout: 60000
            maximum-pool-size: 10
        password: user_esb12
        url: jdbc:oracle:thin:@10.36.126.36:1521/EBDB
        username: USER_ESB
    jackson:
        property-naming-strategy: SNAKE_CASE
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.Oracle10gDialect
    sleuth:
        sampler:
            probability: 1
    zipkin:
        base-url: ${ZIPKIN_SERVICE:http://10.36.126.15:9411/}

eureka:
    client:
        fetchRegistry: true
        registerWithEureka: true
        registryFetchIntervalSeconds: 15
        service-url:
            defaultZone: ${EUREKA_REGISTRY_SERVICE:http://admin:123456@localhost:18001/eureka}
    instance:
        lease-expiration-duration-in-seconds: 5
        lease-renewal-interval-in-seconds: 2
        preferIpAddress: true
info:
    run:
        dir: ${user.dir}
        user: ${user.name}
logging:
    level:
        org:
            springframework:
                data:
                    mongodb:
                        core:
                            MongoTemplate: DEBUG
                web: DEBUG
                web.HttpLogging: INFO
                web.filter.CommonsRequestLoggingFilter: DEBUG
                orm.jpa: DEBUG
                transaction: DEBUG
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE
management:
    endpoints:
        web:
            exposure:
                include: '*'
ribbon:
    ServerListRefreshInterval: 5000
    eureka:
        enabled: true
api:
    sms:
        telegram: https://api.telegram.org/bot1889355399:AAEkD07qKJbyCF7WrmP4wjF_16bkoTRktJQ/sendMessage
file:
    sms:
        prefix: esb-sms-service/data-xml-base/
        xml:
            esb: esb-sms.xml
fpt:
    path:
        login: /oauth2/token
        push-branchname: /api/push-brandname-otp
        check-is-viettel: /api/checkisviettelnumber
        initvec: Banksms@Viettel!
        pricp: MIGEAgEAMBAGByqGSM49AgEGBSuBBAAKBG0wawIBAQQgy7gCMkrwiGowI6O/KGwYtgVTneahwlbLFVByzgzdCCmhRANCAART0e1HmU9GYiYSvb+S58i3kv8sBupjKuq8jcJauueh+C27pwWcmQpZk4wLjYPI5cPXF9w3GTGyiqyk6CWwQr6TPUBVT=MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEe9YVVfiuEbTC8MLFcmettM9z6i1bh49kM97NZJ0yLCZcDQtWhuQ230W/nackSySWO8tErAzDWiMdvEACaHevaA==
        pubcp: MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEU9HtR5lPRmImEr2/kufIt5L/LAbqYyrqvI3CWrrnofgtu6cFnJkKWZOMC42DyOXD1xfcNxkxsoqspOglsEK+kw==

